org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Google 域名走死代理（立即失败），镜像域名直连
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.http.nonProxyHosts=localhost|127.*|[::1]|172.16.*|172.17.*|172.18.*|172.19.*|172.2*|172.30.*|172.31.*|10.*|192.168.*
android.builder.sdkDownload=false
kotlin.compiler.execution.strategy=in-process
